#!/bin/bash
dir="${1:-.}"
find "$dir" -type f -exec sha256sum {} + 2>/dev/null |
sort |
awk '{
    hash=$1
    $1=""
    sub(/^  */, "")
    if (hash == prev) {
        if (!shown) print prevfile
        print
        shown=1
    } else {
        shown=0
    }
    prev=hash
    prevfile=$0
}'
